# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  testing-language-server = {
    pname = "testing-language-server";
    version = "c53cdb6a6b5f8ee6b337c640a16ee3565fac94f2";
    src = fetchgit {
      url = "https://github.com/kbwo/testing-language-server";
      rev = "c53cdb6a6b5f8ee6b337c640a16ee3565fac94f2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-8Nbn4JSVwkyufXMEgcEaCyjT6h7fd/Ypg6Uj2a0F7k0=";
    };
    date = "2025-01-29";
  };
  zola = {
    pname = "zola";
    version = "33f03bb11158464e3ff877cdc5f1c55bbe7337ac";
    src = fetchgit {
      url = "https://github.com/getzola/zola";
      rev = "33f03bb11158464e3ff877cdc5f1c55bbe7337ac";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Ihs0JjOuIBRXdVwPLvHuvXIVnetAbTTXuOL9IDMQAko=";
    };
    date = "2026-03-13";
  };
}
